/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type {
  AudioQuery,
  AudioQueryFromPresetParams,
  AudioQueryParams,
  FrameAudioQuery,
  Score,
  SingFrameAudioQueryParams,
} from "../../models";

import { customInstance } from "../../../../lib/custom-instance";
import type { BodyType } from "../../../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 音声合成用のクエリの初期値を得ます。ここで得られたクエリはそのまま音声合成に利用できます。各値の意味は`Schemas`を参照してください。
 * @summary 音声合成用のクエリを作成する
 */
export const audioQuery = (
  params: AudioQueryParams,
  options?: SecondParameter<typeof customInstance<AudioQuery>>
) => {
  return customInstance<AudioQuery>({ url: `/audio_query`, method: "POST", params }, options);
};
/**
 * 音声合成用のクエリの初期値を得ます。ここで得られたクエリはそのまま音声合成に利用できます。各値の意味は`Schemas`を参照してください。
 * @summary 音声合成用のクエリをプリセットを用いて作成する
 */
export const audioQueryFromPreset = (
  params: AudioQueryFromPresetParams,
  options?: SecondParameter<typeof customInstance<AudioQuery>>
) => {
  return customInstance<AudioQuery>(
    { url: `/audio_query_from_preset`, method: "POST", params },
    options
  );
};
/**
 * 歌唱音声合成用のクエリの初期値を得ます。ここで得られたクエリはそのまま歌唱音声合成に利用できます。各値の意味は`Schemas`を参照してください。
 * @summary 歌唱音声合成用のクエリを作成する
 */
export const singFrameAudioQuery = (
  score: BodyType<Score>,
  params: SingFrameAudioQueryParams,
  options?: SecondParameter<typeof customInstance<FrameAudioQuery>>
) => {
  return customInstance<FrameAudioQuery>(
    {
      url: `/sing_frame_audio_query`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: score,
      params,
    },
    options
  );
};
export type AudioQueryResult = NonNullable<Awaited<ReturnType<typeof audioQuery>>>;
export type AudioQueryFromPresetResult = NonNullable<
  Awaited<ReturnType<typeof audioQueryFromPreset>>
>;
export type SingFrameAudioQueryResult = NonNullable<
  Awaited<ReturnType<typeof singFrameAudioQuery>>
>;
