/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type {
  AudioQuery,
  CancellableSynthesisParams,
  FrameAudioQuery,
  FrameSynthesisParams,
  MorphableTargets200Item,
  MorphableTargetsParams,
  MultiSynthesisParams,
  SynthesisMorphingParams,
  SynthesisParams,
} from "../../models";

import { customInstance } from "../../../../lib/custom-instance";
import type { BodyType } from "../../../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 音声合成する
 */
export const synthesis = (
  audioQuery: BodyType<AudioQuery>,
  params: SynthesisParams,
  options?: SecondParameter<typeof customInstance<Blob>>
) => {
  return customInstance<Blob>(
    {
      url: `/synthesis`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: audioQuery,
      params,
      responseType: "blob",
    },
    options
  );
};
/**
 * @summary 音声合成する（キャンセル可能）
 */
export const cancellableSynthesis = (
  audioQuery: BodyType<AudioQuery>,
  params: CancellableSynthesisParams,
  options?: SecondParameter<typeof customInstance<Blob>>
) => {
  return customInstance<Blob>(
    {
      url: `/cancellable_synthesis`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: audioQuery,
      params,
      responseType: "blob",
    },
    options
  );
};
/**
 * @summary 複数まとめて音声合成する
 */
export const multiSynthesis = (
  audioQuery: AudioQuery[],
  params: MultiSynthesisParams,
  options?: SecondParameter<typeof customInstance<Blob>>
) => {
  return customInstance<Blob>(
    {
      url: `/multi_synthesis`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: audioQuery,
      params,
      responseType: "blob",
    },
    options
  );
};
/**
 * 歌唱音声合成を行います。
 * @summary Frame Synthesis
 */
export const frameSynthesis = (
  frameAudioQuery: BodyType<FrameAudioQuery>,
  params: FrameSynthesisParams,
  options?: SecondParameter<typeof customInstance<Blob>>
) => {
  return customInstance<Blob>(
    {
      url: `/frame_synthesis`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: frameAudioQuery,
      params,
      responseType: "blob",
    },
    options
  );
};
/**
 * 指定されたベーススタイルに対してエンジン内の各キャラクターがモーフィング機能を利用可能か返します。

モーフィングの許可/禁止は`/speakers`の`speaker.supported_features.synthesis_morphing`に記載されています。
プロパティが存在しない場合は、モーフィングが許可されているとみなします。
返り値のスタイルIDはstring型なので注意。
 * @summary 指定したスタイルに対してエンジン内のキャラクターがモーフィングが可能か判定する
 */
export const morphableTargets = (
  morphableTargetsBody: number[],
  params?: MorphableTargetsParams,
  options?: SecondParameter<typeof customInstance<MorphableTargets200Item[]>>
) => {
  return customInstance<MorphableTargets200Item[]>(
    {
      url: `/morphable_targets`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: morphableTargetsBody,
      params,
    },
    options
  );
};
/**
 * 指定された2種類のスタイルで音声を合成、指定した割合でモーフィングした音声を得ます。

モーフィングの割合は`morph_rate`で指定でき、0.0でベースのスタイル、1.0でターゲットのスタイルに近づきます。
 * @summary 2種類のスタイルでモーフィングした音声を合成する
 */
export const synthesisMorphing = (
  audioQuery: BodyType<AudioQuery>,
  params: SynthesisMorphingParams,
  options?: SecondParameter<typeof customInstance<Blob>>
) => {
  return customInstance<Blob>(
    {
      url: `/synthesis_morphing`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: audioQuery,
      params,
      responseType: "blob",
    },
    options
  );
};
export type SynthesisResult = NonNullable<Awaited<ReturnType<typeof synthesis>>>;
export type CancellableSynthesisResult = NonNullable<
  Awaited<ReturnType<typeof cancellableSynthesis>>
>;
export type MultiSynthesisResult = NonNullable<Awaited<ReturnType<typeof multiSynthesis>>>;
export type FrameSynthesisResult = NonNullable<Awaited<ReturnType<typeof frameSynthesis>>>;
export type MorphableTargetsResult = NonNullable<Awaited<ReturnType<typeof morphableTargets>>>;
export type SynthesisMorphingResult = NonNullable<Awaited<ReturnType<typeof synthesisMorphing>>>;
