/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX BFF
 * VOICEVOXのBFF
 * OpenAPI spec version: latest
 */

export * from "./synthesisTalk400";
export * from "./synthesisTalkParams";
