/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { Mora } from "./mora";

/**
 * アクセント句ごとの情報。
 */
export interface AccentPhrase {
  /** モーラのリスト */
  moras: Mora[];
  /** アクセント箇所 */
  accent: number;
  /** アクセント句の末尾につく無音モーラ。null の場合は無音モーラを付けない。 */
  pause_mora?: Mora;
  /** 疑問系かどうか */
  is_interrogative?: boolean;
}
