/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

export type AudioQueryParams = {
  text: string;
  speaker: number;
  enable_katakana_english?: boolean;
  core_version?: string;
};
