/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { CorsPolicyMode } from "./corsPolicyMode";

export interface BodySettingPostSettingPost {
  cors_policy_mode: CorsPolicyMode;
  allow_origin?: string;
}
