/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * CORSの許可モード。
 */
export type CorsPolicyMode = (typeof CorsPolicyMode)[keyof typeof CorsPolicyMode];

export const CorsPolicyMode = {
  all: "all",
  localapps: "localapps",
} as const;
