/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { LibrarySpeaker } from "./librarySpeaker";

/**
 * ダウンロード可能な音声ライブラリの情報。
 */
export interface DownloadableLibraryInfo {
  /** 音声ライブラリの名前 */
  name: string;
  /** 音声ライブラリのUUID */
  uuid: string;
  /** 音声ライブラリのバージョン */
  version: string;
  /** 音声ライブラリのダウンロードURL */
  download_url: string;
  /** 音声ライブラリのバイト数 */
  bytes: number;
  /** 音声ライブラリに含まれるキャラクターのリスト */
  speakers: LibrarySpeaker[];
}
