/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { LicenseInfo } from "./licenseInfo";
import type { SupportedFeatures } from "./supportedFeatures";
import type { UpdateInfo } from "./updateInfo";

/**
 * エンジン自体に関する情報。
 */
export interface EngineManifest {
  /** マニフェストのバージョン */
  manifest_version: string;
  /** エンジン名 */
  name: string;
  /** ブランド名 */
  brand_name: string;
  /** エンジンのUUID */
  uuid: string;
  /** エンジンのURL */
  url: string;
  /** エンジンのアイコンをBASE64エンコードしたもの */
  icon: string;
  /** デフォルトのサンプリング周波数 */
  default_sampling_rate: number;
  /** エンジンのフレームレート */
  frame_rate: number;
  /** エンジンの利用規約 */
  terms_of_service: string;
  /** エンジンのアップデート情報 */
  update_infos: UpdateInfo[];
  /** 依存関係のライセンス情報 */
  dependency_licenses: LicenseInfo[];
  /** エンジンが対応するvvlibのバージョン */
  supported_vvlib_manifest_version?: string;
  /** エンジンが持つ機能 */
  supported_features: SupportedFeatures;
}
