/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

export type FrameSynthesisParams = {
  speaker: number;
  core_version?: string;
};
