/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * 音素の情報。
 */
export interface FramePhoneme {
  /** 音素 */
  phoneme: string;
  /** 音素のフレーム長 */
  frame_length: number;
  /** 音符のID */
  note_id?: string | null;
}
