/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { FramePhoneme } from "./framePhoneme";

/**
 * フレームごとの音声合成用のクエリ。
 */
export interface FrameAudioQuery {
  /** フレームごとの基本周波数 */
  f0: number[];
  /** フレームごとの音量 */
  volume: number[];
  /** 音素のリスト */
  phonemes: FramePhoneme[];
  /** 全体の音量 */
  volumeScale: number;
  /** 音声データの出力サンプリングレート */
  outputSamplingRate: number;
  /** 音声データをステレオ出力するか否か */
  outputStereo: boolean;
}
