/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { Speaker } from "./speaker";
import type { SpeakerInfo } from "./speakerInfo";

/**
 * 音声ライブラリに含まれるキャラクターの情報。
 */
export interface LibrarySpeaker {
  speaker: Speaker;
  speaker_info: SpeakerInfo;
}
