/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * 依存ライブラリのライセンス情報。
 */
export interface LicenseInfo {
  /** 依存ライブラリ名 */
  name: string;
  /** 依存ライブラリのバージョン */
  version?: string;
  /** 依存ライブラリのライセンス名 */
  license?: string;
  /** 依存ライブラリのライセンス本文 */
  text: string;
}
