/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * モーラ（子音＋母音）ごとの情報。
 */
export interface Mora {
  /** 文字 */
  text: string;
  /** 子音の音素 */
  consonant?: string;
  /** 子音の長さ */
  consonant_length?: number;
  /** 母音の音素 */
  vowel: string;
  /** 母音の長さ */
  vowel_length: number;
  /** 音高 */
  pitch: number;
}
