/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { MorphableTargetInfo } from "./morphableTargetInfo";

export type MorphableTargets200Item = { [key: string]: MorphableTargetInfo };
