/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * モーフィング相手としての情報。
 */
export interface MorphableTargetInfo {
  /** 指定したキャラクターに対してモーフィングの可否 */
  is_morphable: boolean;
}
