/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

export type MultiSynthesisParams = {
  speaker: number;
  /**
   * 疑問系のテキストが与えられたら語尾を自動調整する
   */
  enable_interrogative_upspeak?: boolean;
  core_version?: string;
};
