/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * 音符ごとの情報。
 */
export interface Note {
  /** ID */
  id?: string | null;
  /** 音階 */
  key?: number;
  /** 音符のフレーム長 */
  frame_length: number;
  /** 音符の歌詞 */
  lyric: string;
}
