/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * エラーを起こした箇所
 */
export type ParseKanaBadRequestErrorArgs = { [key: string]: string };
