/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { Note } from "./note";

/**
 * 楽譜情報。
 */
export interface Score {
  /** 音符のリスト */
  notes: Note[];
}
