/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * モーフィング機能への対応。'ALL' は「全て許可」、'SELF_ONLY' は「同じキャラクター内でのみ許可」、'NOTHING' は「全て禁止」
 */
export type SpeakerSupportedFeaturesPermittedSynthesisMorphing =
  (typeof SpeakerSupportedFeaturesPermittedSynthesisMorphing)[keyof typeof SpeakerSupportedFeaturesPermittedSynthesisMorphing];

export const SpeakerSupportedFeaturesPermittedSynthesisMorphing = {
  ALL: "ALL",
  SELF_ONLY: "SELF_ONLY",
  NOTHING: "NOTHING",
} as const;
