/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { SpeakerSupportedFeaturesPermittedSynthesisMorphing } from "./speakerSupportedFeaturesPermittedSynthesisMorphing";

/**
 * キャラクターの対応機能の情報
 */
export interface SpeakerSupportedFeatures {
  /** モーフィング機能への対応。'ALL' は「全て許可」、'SELF_ONLY' は「同じキャラクター内でのみ許可」、'NOTHING' は「全て禁止」 */
  permitted_synthesis_morphing?: SpeakerSupportedFeaturesPermittedSynthesisMorphing;
}
