/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { SpeakerStyle } from "./speakerStyle";
import type { SpeakerSupportedFeatures } from "./speakerSupportedFeatures";

/**
 * キャラクター情報
 */
export interface Speaker {
  /** 名前 */
  name: string;
  /** キャラクターのUUID */
  speaker_uuid: string;
  /** スタイルの一覧 */
  styles: SpeakerStyle[];
  /** キャラクターのバージョン */
  version: string;
  /** キャラクターの対応機能 */
  supported_features?: SpeakerSupportedFeatures;
}
