/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * スタイルの種類。talk:音声合成クエリの作成と音声合成が可能。singing_teacher:歌唱音声合成用のクエリの作成が可能。frame_decode:歌唱音声合成が可能。sing:歌唱音声合成用のクエリの作成と歌唱音声合成が可能。
 */
export type SpeakerStyleType = (typeof SpeakerStyleType)[keyof typeof SpeakerStyleType];

export const SpeakerStyleType = {
  talk: "talk",
  singing_teacher: "singing_teacher",
  frame_decode: "frame_decode",
  sing: "sing",
} as const;
