/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { SpeakerStyleType } from "./speakerStyleType";

/**
 * キャラクターのスタイル情報
 */
export interface SpeakerStyle {
  /** スタイル名 */
  name: string;
  /** スタイルID */
  id: number;
  /** スタイルの種類。talk:音声合成クエリの作成と音声合成が可能。singing_teacher:歌唱音声合成用のクエリの作成が可能。frame_decode:歌唱音声合成が可能。sing:歌唱音声合成用のクエリの作成と歌唱音声合成が可能。 */
  type?: SpeakerStyleType;
}
