/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */
import type { StyleInfo } from "./styleInfo";

/**
 * キャラクターの追加情報
 */
export interface SpeakerInfo {
  /** policy.md */
  policy: string;
  /** 立ち絵画像をbase64エンコードしたもの、あるいはURL */
  portrait: string;
  /** スタイルの追加情報 */
  style_infos: StyleInfo[];
}
