/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * スタイルの追加情報
 */
export interface StyleInfo {
  /** スタイルID */
  id: number;
  /** このスタイルのアイコンをbase64エンコードしたもの、あるいはURL */
  icon: string;
  /** このスタイルの立ち絵画像をbase64エンコードしたもの、あるいはURL */
  portrait?: string;
  /** サンプル音声をbase64エンコードしたもの、あるいはURL */
  voice_samples: string[];
}
