/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * 対応しているデバイスの情報。
 */
export interface SupportedDevicesInfo {
  /** CPUに対応しているか */
  cpu: boolean;
  /** CUDA(Nvidia GPU)に対応しているか */
  cuda: boolean;
  /** DirectML(Nvidia GPU/Radeon GPU等)に対応しているか */
  dml: boolean;
}
