/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * エンジンのアップデート情報。
 */
export interface UpdateInfo {
  /** エンジンのバージョン名 */
  version: string;
  /** アップデートの詳細についての説明 */
  descriptions: string[];
  /** 貢献者名 */
  contributors?: string[];
}
