/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
