/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * vvlib(VOICEVOX Library)に関する情報。
 */
export interface VvlibManifest {
  /** マニフェストバージョン */
  manifest_version: string;
  /** 音声ライブラリ名 */
  name: string;
  /** 音声ライブラリバージョン */
  version: string;
  /** 音声ライブラリのUUID */
  uuid: string;
  /** エンジンのブランド名 */
  brand_name: string;
  /** エンジン名 */
  engine_name: string;
  /** エンジンのUUID */
  engine_uuid: string;
}
