/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 * OpenAPI spec version: latest
 */

/**
 * 品詞
 */
export type WordTypes = (typeof WordTypes)[keyof typeof WordTypes];

export const WordTypes = {
  PROPER_NOUN: "PROPER_NOUN",
  COMMON_NOUN: "COMMON_NOUN",
  VERB: "VERB",
  ADJECTIVE: "ADJECTIVE",
  SUFFIX: "SUFFIX",
} as const;
