name: Terraform Deploy

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Lambda Layer
        run: |
          # 1. 確実に作業ディレクトリを特定
          TARGET_DIR="infra/modules/lambda-node-api"

          # 2. 以前の残骸（Gitから降ってきた空Zipなど）を完全に消す
          rm -f $TARGET_DIR/layer.zip

          # 3. nodejsフォルダの準備
          mkdir -p $TARGET_DIR/nodejs
          cp backend/package.json $TARGET_DIR/nodejs/
          cp backend/package-lock.json $TARGET_DIR/nodejs/

          # 4. インストール実行
          cd $TARGET_DIR/nodejs
          npm install --omit=dev

          # 5. 一つ上のディレクトリに戻って新規に Zip 作成
          cd ..
          zip -r layer.zip nodejs/

          # 6. 確認用（ログにファイルサイズを出して、0バイトじゃないかチェック）
          ls -lh layer.zip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # TFCのUser Settings > Tokensで発行したトークンをGitHubのSecretに登録
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/environments/dev

      - name: Terraform Apply(Manual)
        # plan だけを実行する
        run: terraform apply -input=false
        working-directory: ./infra/environments/dev
