name: Terraform Deploy

on:
  push:
    branches: [develop]
    paths:
      - "backend/**"
      - "infra/**"
      - ".github/workflows/**" # ワークフロー自体
  pull_request:
    branches: [develop]
    paths:
      - "backend/**" # Lambdaのソースコード
      - "infra/**" # Terraformコード
      - ".github/workflows/**" # ワークフロー自体

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # コードの読み取り
      pull-requests: write # PRへのコメント書き込み権限
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Lambda Layer
        # キャッシュがヒットした（＝package-lockが同じ）場合はビルドをスキップ
        # if: steps.cache-zip.outputs.cache-hit != 'true'
        run: |
          # 作業用の一時親ディレクトリを作成
          BASE_DIR="infra/modules/lambda-node-api/layer_content"
          # 1. 確実に作業ディレクトリを特定
          TARGET_DIR="$BASE_DIR/nodejs"

          mkdir -p $TARGET_DIR
          cp backend/package.json $TARGET_DIR/
          cp backend/package-lock.json $TARGET_DIR/

          npm ci --omit=dev --prefix $TARGET_DIR

          # 確認: layer_content の直下に nodejs がある状態にする
          ls -d $TARGET_DIR
          echo "Layer directory structure prepared at $TARGET_DIR"

      - name: Build API
        run: |
          cd backend
          npm ci
          npm run build
          mkdir -p ../infra/modules/lambda-node-api/api_content
          cp -r dist/* ../infra/modules/lambda-node-api/api_content/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # TFCのUser Settings > Tokensで発行したトークンをGitHubのSecretに登録
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/environments/dev

        # PR作成時に Plan を実行して結果をコメントする
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -no-color
        working-directory: ./infra/environments/dev
        continue-on-error: true

      - name: Post Plan to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`

            <details><summary>詳細なログを表示</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: terraform apply -auto-approve
        working-directory: ./infra/environments/dev
